Decomplect lagging analyses
twashing/ibgateway pull request #16
Opened 2018-09-09 23:43 UTC by xiongtx

2018-09-09 23:51 UTC, twashing requested changes
Before replacing the existing sma, ema and bb, we'll need to apply this to the processing pipeline and see the results.

2018-09-09 23:54 UTC, xiongtx commented
These functions are decomplected from the pipeline and unit-testable. To the EMA and BB in the pipeline, we'll have to refactor the pipeline (a worthwhile endeavor IMO).

2018-09-10 00:10 UTC, twashing requested changes
Agreed. That refactoring will use Onyx.

So we can keep these around, pending the added test and test run of the updated `simple-moving-average` function. 👍

2018-09-10 00:10 UTC, twashing commented on src/clojure/com/interrupt/edgar/core/analysis/lagging.clj
> +            (reverse xs))))
Why are we reversing the list here. The time orientation should be from left -> right.

2018-09-10 00:10 UTC, twashing commented on src/clojure/com/interrupt/edgar/core/analysis/lagging.clj
> +        (assoc output (math/mean xs) :population ticks))))
Also, since `simple-moving-average` has changed, can you add a test, and try streaming it to your browser?

2018-09-10 00:28 UTC, xiongtx commented on src/clojure/com/interrupt/edgar/core/analysis/lagging.clj
> +            (reverse xs))))
Yes, you're right

2018-09-11 02:24 UTC, xiongtx commented on src/clojure/com/interrupt/edgar/core/analysis/lagging.clj
> +        (assoc output (math/mean xs) :population ticks))))
There's an existing test (`sample-moving-average-test`) that didn't work, so I cleaned it up; now it works.

2018-09-11 02:25 UTC, xiongtx commented
I think this should be good to merge.

2018-09-11 03:54 UTC, twashing approved these changes

2018-09-11 03:55 UTC, twashing commented
Cool. This one's working great. In the latest master though, `switchboard/record-live-data` has disappeared. So maybe just rebase and run it before merging. For sure some symbols have disappeared.

Otherwise it looks good. 👍

2018-09-11 04:12 UTC, merged