Implement scanner data flow
twashing/ibgateway pull request #25
Opened 2018-09-15 23:49 UTC by xiongtx

2018-09-16 03:01 UTC, twashing requested changes
Code patterns looks really good. I left a few comments.

Also, I wasn't sure how to use those *main* functions. I set up my attempt on [this workbench](https://github.com/twashing/ibgateway/blob/market-scanner/workbench/clojure/com/interrupt/ibgateway/core.clj#L336).

Keeping in mind that those scan subscriptions are always streaming new values,  how are we say, keeping a kind leaderboard of `volatility`, `volume` and `price` changes.

We can step through the [example code](https://github.com/twashing/ibgateway/blob/master/workbench/clojure/com/interrupt/ibgateway/core.clj#L438) if need be. My connection is back up.

Thanks!

2018-09-16 03:01 UTC, twashing commented on src/clojure/com/interrupt/ibgateway/component/ewrapper_impl.clj
> +(def scan-codes (->> ScanCode .getEnumConstants (map str) sort))
Not all of these scan codes describe high price movement. We'll definitely want to focus on those.

I've singled out a [few here](https://github.com/twashing/ibgateway/blob/master/workbench/clojure/com/interrupt/ibgateway/core.clj#L447).

2018-09-16 03:01 UTC, twashing commented on src/clojure/com/interrupt/edgar/scanner.clj
> +                 (<! hot-by-price-range-ch)]]
These guys could come in at different velocities. Some might not be active at all. So this could block for a long while.

2018-09-16 03:31 UTC, xiongtx commented
On the feedback, perhaps we need to discuss the design a bit more. My understanding is:

- Query for securities based on various scan codes
- Find a security among all those returned by some metric 
  - I implemented most frequently appearing b/c it's relatively simple
- Some downstream consumer will consume the security and adjust the pipeline to process values of that security
  - Yet to be implemented

2018-09-16 03:33 UTC, xiongtx commented on src/clojure/com/interrupt/edgar/scanner.clj
> +                 (<! hot-by-price-range-ch)]]
Is that true? I haven't tried them all, but my understanding is that the request will periodically trigger a query and return `n` values.

2018-09-16 03:35 UTC, xiongtx commented on src/clojure/com/interrupt/ibgateway/component/ewrapper_impl.clj
> +(def scan-codes (->> ScanCode .getEnumConstants (map str) sort))
Those are the ones that are utilized in `scanner-decide`.

Here we just list out the scan codes and create channels for them regardless of which we use (I prefer to be systematic).

2018-09-16 15:05 UTC, twashing commented on src/clojure/com/interrupt/ibgateway/component/ewrapper_impl.clj
> +(def scan-codes (->> ScanCode .getEnumConstants (map str) sort))
Ok, that's fine. Let's create a subset of `scan-codes`, that'll just be the ones we're using. No need to have a bunch of channels (in `scanner-chs`) that will never get used.

2018-09-16 15:06 UTC, twashing commented
Maybe we can go over the design at 11:30 or noon? Let me know what works.

2018-09-18 02:02 UTC, twashing approved these changes

2018-09-18 02:03 UTC, twashing commented
Cool man. Great work. 👍

2018-09-18 02:03 UTC, merged